ecbuild_set_verbose( ENABLE_MPI  OFF  CACHE BOOL "MPI" )

ecbuild_set_verbose( ENABLE_PYTHON OFF CACHE BOOL "Python disabled" )

ecbuild_set_verbose( ENABLE_FDB5        ON  CACHE BOOL "FDB5 enabled in client" )
ecbuild_set_verbose( ENABLE_MIR_TOOLS   ON  CACHE BOOL "Install MIR tools" )

ecbuild_set_verbose( ENABLE_EXPERIMENTAL  OFF   CACHE BOOL "experimental stuff" )
ecbuild_set_verbose( ENABLE_AEC           ON    CACHE BOOL "eccodes AEC aka SZip encoding" )
ecbuild_set_verbose( ENABLE_EIGEN         ON    CACHE BOOL "eigen support" )
ecbuild_set_verbose( ENABLE_JPG           OFF   CACHE BOOL "eccodes JPG encoding" )
ecbuild_set_verbose( ENABLE_FDB           OFF   CACHE BOOL "Both for FDB4 (client) and FDB5 (server)" )

ecbuild_set_verbose( ENABLE_MEMFS            ON    CACHE BOOL "eccodes definitions in memory" )
ecbuild_set_verbose( ENABLE_TESSELATION      OFF   CACHE BOOL " " )
ecbuild_set_verbose( ENABLE_ODB2             ON    CACHE BOOL " " )
ecbuild_set_verbose( ENABLE_BUFR             ON    CACHE BOOL " " )
ecbuild_set_verbose( ENABLE_FDB              ON    CACHE BOOL " " )
ecbuild_set_verbose( ENABLE_FFTW             ON    CACHE BOOL "for atlas support of SH transforms" )
ecbuild_set_verbose( ENABLE_PROJ             ON    CACHE BOOL " " )
ecbuild_set_verbose( ENABLE_ECKIT_GEO        OFF   CACHE BOOL " " )
ecbuild_set_verbose( ENABLE_ECKIT_CODEC      OFF   CACHE BOOL " " )
ecbuild_set_verbose( BUNDLE_SKIP_GRIBJUMP    OFF   CACHE BOOL " " )
ecbuild_set_verbose( ENABLE_SINGLE_PRECISION OFF   CACHE BOOL "for libemos" )
ecbuild_set_verbose( ECMWF                   ON    CACHE BOOL " " )

ecbuild_set_verbose( BUNDLE_SKIP_FDB                ON CACHE BOOL   "disable FDB4" )
ecbuild_set_verbose( BUNDLE_SKIP_LIBEMOS                ON CACHE BOOL "disable libemos" )
ecbuild_set_verbose( ENABLE_PPROC_EMOS              OFF CACHE BOOL " " )
ecbuild_set_verbose( ENABLE_RPC             OFF CACHE BOOL "RPC no longer needed" )
