name: CD (Nightly)

on:
    push:
        branches:
            - "nightly"
            - "feature/MARSC-413-nightly-builds"
        tags-ignore:
            - "**"

    # pull_request: ~

    # for manual trigger
    # workflow_dispatch: ~

jobs:
    nexus:
        uses: ecmwf/reusable-workflows/.github/workflows/create-package.yml@v2
        secrets: inherit
        with:
            skip_checks: true
            restrict_matrix_jobs: gnu@rocky-9.5
            build_config: .github/cd-config/build-nightly.yml

    # hpc builds (gnu/intel)
    hpc:
        uses: ecmwf/reusable-workflows/.github/workflows/cd-module.yml@clean-nightly-builds
        secrets: inherit
        with:
            clean_before_install: true
            skip_checks: true
            platforms: |
                gnu-8.5.0
                intel-2021.4.0
            config_path: .github/cd-config/build-hpc-nightly.yml
        # disable concurrency to prevent rsync clashes
        concurrency:
            group: hpc-nightly
            cancel-in-progress: true
