name: CD (Nightly)

on:
    push:
        branches:
            - "nightly"
            - "feature/MARSC-413-nightly-builds"
        tags-ignore:
            - "**"

jobs:
    hpc:
        uses: ecmwf/reusable-workflows/.github/workflows/cd-module.yml@v4
        secrets: inherit
        with:
            skip_checks: true
            platforms: |
                gnu-8.5.0
                intel-2021.4.0
            config_path: .github/cd-config/build-hpc-nightly.yml
        # disable concurrency to prevent rsync clashes
        concurrency:
            group: hpc-nightly
            cancel-in-progress: true
